(()=>{
const NS='http://www.w3.org/2000/svg',visible={hk:true,cn:true},tip=document.querySelector('#tooltip');let model;
const $=s=>document.querySelector(s),fmt=n=>'¥'+Math.round(n).toLocaleString()+'/克',date=s=>new Date(s+'T00:00:00Z'),stamp=d=>d.getTime(),key=d=>d.toISOString().slice(0,10);
function el(p,n,a={},t=''){const x=document.createElementNS(NS,n);Object.entries(a).forEach(([k,v])=>x.setAttribute(k,v));if(t)x.textContent=t;p.appendChild(x);return x}
function scale(d,r){const z=d[1]-d[0]||1;return v=>r[0]+(v-d[0])/z*(r[1]-r[0])}function bounds(a){return[Math.min(...a),Math.max(...a)]}function nearest(a,t){return a.reduce((x,y)=>Math.abs(stamp(y.date)-t)<Math.abs(stamp(x.date)-t)?y:x,a[0])}function md(d){return String(d.getUTCMonth()+1).padStart(2,'0')+'-'+String(d.getUTCDate()).padStart(2,'0')}function path(a,x,y,f){return a.map((d,i)=>(i?'L':'M')+x(stamp(d.date)).toFixed(1)+','+y(d[f]).toFixed(1)).join(' ')}
function setup(node){const width=Math.max(320,node.parentElement.clientWidth),height=width<480?280:320,m={t:12,r:18,b:48,l:66},w=width-m.l-m.r,h=height-m.t-m.b;node.classList.remove('skeleton');node.replaceChildren();node.setAttribute('viewBox',`0 0 ${width} ${height}`);return{width,w,h,g:el(node,'g',{transform:`translate(${m.l},${m.t})`})}}
function axes(g,x,y,xd,yd,w,h,width,title,indexed){el(g,'rect',{class:'chart-frame',width:w,height:h});for(let i=0;i<5;i++){const v=yd[0]+(yd[1]-yd[0])*i/4,py=y(v);el(g,'line',{class:'grid',x1:0,x2:w,y1:py,y2:py});el(g,'text',{class:'axis-text',x:-9,y:py+4,'text-anchor':'end'},indexed?v.toFixed(0):Math.round(v).toLocaleString())}const c=width<480?4:6;for(let i=0;i<c;i++){const v=xd[0]+(xd[1]-xd[0])*i/(c-1),px=x(v);el(g,'text',{class:'axis-text',x:px,y:h+20,'text-anchor':i===0?'start':i===c-1?'end':'middle'},md(new Date(v)))}el(g,'text',{class:'axis-title',x:w/2,y:h+42,'text-anchor':'middle'},'日期');el(g,'text',{class:'axis-title',transform:'rotate(-90)',x:-h/2,y:-50,'text-anchor':'middle'},title)}
function tooltip(e,html){tip.innerHTML=html;tip.style.display='block';tip.style.left=Math.min(innerWidth-230,e.clientX+12)+'px';tip.style.top=Math.max(8,e.clientY-22)+'px'}
function pairChart(id,indexed){const node=$(id),{width,w,h,g}=setup(node),baseH=model.hk[0].value,baseC=model.cn[0].value,data={hk:model.hk.map(d=>({...d,plot:indexed?d.value/baseH*100:d.value})),cn:model.cn.map(d=>({...d,plot:indexed?d.value/baseC*100:d.value}))},all=[...data.hk,...data.cn],xd=bounds(all.map(d=>stamp(d.date))),b=bounds(all.map(d=>d.plot)),pad=(b[1]-b[0])*.12,yd=[b[0]-pad,b[1]+pad],x=scale(xd,[0,w]),y=scale(yd,[h,0]);axes(g,x,y,xd,yd,w,h,width,indexed?'指数':'人民币/克',indexed);['hk','cn'].forEach(s=>{if(!visible[s])return;el(g,'path',{class:'series-'+s,d:path(data[s],x,y,'plot')});data[s].forEach(d=>el(g,'circle',{class:'dot-'+s,cx:x(stamp(d.date)),cy:y(d.plot),r:2.8}));if(!indexed){const d=data[s].at(-1);el(g,'text',{class:'value-label',x:w-5,y:y(d.plot)+(s==='hk'?16:-8),'text-anchor':'end'},(s==='hk'?'香港 ':'大陆 ')+fmt(d.value))}});const guide=el(g,'line',{class:'guide',y1:0,y2:h,display:'none'}),hit=el(g,'rect',{class:'hit',width:w,height:h});hit.addEventListener('pointermove',e=>{const r=hit.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width*w,t=xd[0]+mx/w*(xd[1]-xd[0]),hd=visible.hk?nearest(data.hk,t):null,cd=visible.cn?nearest(data.cn,t):null,rows=[];guide.setAttribute('x1',mx);guide.setAttribute('x2',mx);guide.removeAttribute('display');if(hd)rows.push('香港：'+fmt(hd.value));if(cd)rows.push('大陆：'+fmt(cd.value));if(hd&&cd&&!indexed)rows.push('价差：'+fmt(cd.value-hd.value));tooltip(e,`<b>${key(new Date(t))}</b><br>${rows.join('<br>')}`)});hit.addEventListener('pointerleave',()=>{guide.setAttribute('display','none');tip.style.display='none'})}
function gapChart(){const node=$('#gap-chart'),{width,w,h,g}=setup(node),hm=new Map(model.hk.map(d=>[key(d.date),d])),gap=model.cn.filter(d=>hm.has(key(d.date))).map(d=>({date:d.date,cn:d.value,hk:hm.get(key(d.date)).value,value:d.value-hm.get(key(d.date)).value})),xd=bounds(gap.map(d=>stamp(d.date))),b=bounds(gap.map(d=>d.value)),pad=(b[1]-b[0])*.18,yd=[b[0]-pad,b[1]+pad],x=scale(xd,[0,w]),y=scale(yd,[h,0]);axes(g,x,y,xd,yd,w,h,width,'人民币/克',false);el(g,'path',{class:'series-gap',d:path(gap,x,y,'value')});gap.forEach(d=>el(g,'circle',{class:'dot-gap',cx:x(stamp(d.date)),cy:y(d.value),r:3.2}));const d=gap.at(-1);el(g,'text',{class:'value-label',x:w-5,y:y(d.value)-9,'text-anchor':'end'},'最新 '+fmt(d.value));const hit=el(g,'rect',{class:'hit',width:w,height:h});hit.addEventListener('pointermove',e=>{const r=hit.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width*w,t=xd[0]+mx/w*(xd[1]-xd[0]),v=nearest(gap,t);tooltip(e,`<b>${key(v.date)}</b><br>大陆：${fmt(v.cn)}<br>香港：${fmt(v.hk)}<br>价差：${fmt(v.value)}`)});hit.addEventListener('pointerleave',()=>tip.style.display='none')}
function insights(){const hp=model.hk.at(-1),cp=model.cn.at(-1),hpp=model.hk.at(-2),cpp=model.cn.at(-2),gap=cp.value-hp.value,old=cpp.value-hpp.value,hMove=hp.value-hpp.value,cMove=cp.value-cpp.value,hTrend=(hp.value/model.hk[0].value-1)*100,cTrend=(cp.value/model.cn[0].value-1)*100;$('#updated').textContent=model.updated_at+'（香港/北京时间）';$('#updated').dateTime=model.updated_at;$('#latest-gap').textContent=fmt(gap);$('#price-title').textContent=cMove<0?'大陆回落，香港相对稳定':'两地最新报价更新';$('#price-copy').textContent=`大陆 ${fmt(cp.value)}，较前值${cMove>=0?'增加':'下降'} ${fmt(Math.abs(cMove))}；香港折算 ${fmt(hp.value)}，较前值${Math.abs(hMove)<.5?'基本持平':(hMove>0?'上升 ':'下降 ')+fmt(Math.abs(hMove))}。`;$('#trend-title').textContent='两地走势出现'+(Math.sign(hTrend)===Math.sign(cTrend)?'同步':'分化');$('#trend-copy').textContent=`区间内香港${hTrend>=0?'上涨':'下跌'} ${Math.abs(hTrend).toFixed(1)}%，大陆${cTrend>=0?'上涨':'下跌'} ${Math.abs(cTrend).toFixed(1)}%。`;$('#gap-title').textContent=`最新价差 ${fmt(gap)}`;$('#gap-copy').textContent=`较前值${gap-old>=0?'扩大':'缩小'} ${fmt(Math.abs(gap-old))}；大陆挂牌价比香港折算价高 ${(gap/hp.value*100).toFixed(1)}%。口径差异意味着这并非直接套利空间。`}
function draw(){pairChart('#price-chart',false);pairChart('#index-chart',true);gapChart()}async function init(){try{const raw=await fetch('./data/prices.json',{cache:'no-store'});if(!raw.ok)throw Error('HTTP '+raw.status);const d=await raw.json();model={...d,hk:d.hk.map(x=>({...x,date:date(x.date)})),cn:d.cn.map(x=>({...x,date:date(x.date)}))};insights();draw()}catch(e){$('#error').hidden=false;$('#error').textContent='价格数据加载失败：'+e.message}}
document.querySelectorAll('[data-series]').forEach(b=>b.addEventListener('click',()=>{const s=b.dataset.series;visible[s]=!visible[s];b.setAttribute('aria-pressed',visible[s]);draw()}));let width=0,timer;new ResizeObserver(e=>{const w=Math.round(e[0].contentRect.width);if(!model||w===width)return;width=w;clearTimeout(timer);timer=setTimeout(draw,80)}).observe(document.querySelector('.page'));init();
})();
